

wandb offline 

CUDA_VISIBLE_DEVICES=0   train_scl_amlp_v4.py --alpha=0.5 --augNearRate=1000  --ent_open_scale=0.2 --gamma=0.1 --lr=0.02 --min_step=10000 --sigmaP=10 --sour_aug=0 --v_latent=10 --augNearRate=100000 --data_aug_crop 0.8 --config=configs/officehome-train-config_OPDA.yaml --source_data=./txt/source_Real_univ_zzl.txt    --target_data=./txt/target_Art_univ_zzl.txt      &
CUDA_VISIBLE_DEVICES=1   train_scl_amlp_v4.py --alpha=0.5 --augNearRate=1000  --ent_open_scale=0.2 --gamma=0.1 --lr=0.02 --min_step=10000 --sigmaP=10 --sour_aug=0 --v_latent=10 --augNearRate=100000 --data_aug_crop 0.8 --config=configs/officehome-train-config_OPDA.yaml --source_data=./txt/source_Real_univ_zzl.txt    --target_data=./txt/target_Clipart_univ_zzl.txt  &
CUDA_VISIBLE_DEVICES=2   train_scl_amlp_v4.py --alpha=0.5 --augNearRate=1000  --ent_open_scale=0.2 --gamma=0.1 --lr=0.02 --min_step=10000 --sigmaP=10 --sour_aug=0 --v_latent=10 --augNearRate=100000 --data_aug_crop 0.8 --config=configs/officehome-train-config_OPDA.yaml --source_data=./txt/source_Real_univ_zzl.txt    --target_data=./txt/target_Product_univ_zzl.txt  &
CUDA_VISIBLE_DEVICES=3   train_scl_amlp_v4.py --alpha=0.5 --augNearRate=1000  --ent_open_scale=0.2 --gamma=0.1 --lr=0.02 --min_step=10000 --sigmaP=10 --sour_aug=0 --v_latent=10 --augNearRate=100000 --data_aug_crop 0.8 --config=configs/officehome-train-config_OPDA.yaml --source_data=./txt/source_Product_univ_zzl.txt --target_data=./txt/target_Art_univ_zzl.txt      &
CUDA_VISIBLE_DEVICES=4   train_scl_amlp_v4.py --alpha=0.5 --augNearRate=1000  --ent_open_scale=0.2 --gamma=0.1 --lr=0.02 --min_step=10000 --sigmaP=10 --sour_aug=0 --v_latent=10 --augNearRate=100000 --data_aug_crop 0.8 --config=configs/officehome-train-config_OPDA.yaml --source_data=./txt/source_Product_univ_zzl.txt --target_data=./txt/target_Clipart_univ_zzl.txt  &
CUDA_VISIBLE_DEVICES=5   train_scl_amlp_v4.py --alpha=0.5 --augNearRate=1000  --ent_open_scale=0.2 --gamma=0.1 --lr=0.02 --min_step=10000 --sigmaP=10 --sour_aug=0 --v_latent=10 --augNearRate=100000 --data_aug_crop 0.8 --config=configs/officehome-train-config_OPDA.yaml --source_data=./txt/source_Product_univ_zzl.txt --target_data=./txt/target_Real_univ_zzl.txt     &
CUDA_VISIBLE_DEVICES=6   train_scl_amlp_v4.py --alpha=0.5 --augNearRate=1000  --ent_open_scale=0.2 --gamma=0.1 --lr=0.02 --min_step=10000 --sigmaP=10 --sour_aug=0 --v_latent=10 --augNearRate=100000 --data_aug_crop 0.8 --config=configs/officehome-train-config_OPDA.yaml --source_data=./txt/source_Clipart_univ_zzl.txt --target_data=./txt/target_Art_univ_zzl.txt      &
CUDA_VISIBLE_DEVICES=7   train_scl_amlp_v4.py --alpha=0.5 --augNearRate=1000  --ent_open_scale=0.2 --gamma=0.1 --lr=0.02 --min_step=10000 --sigmaP=10 --sour_aug=0 --v_latent=10 --augNearRate=100000 --data_aug_crop 0.8 --config=configs/officehome-train-config_OPDA.yaml --source_data=./txt/source_Clipart_univ_zzl.txt --target_data=./txt/target_Product_univ_zzl.txt  &
CUDA_VISIBLE_DEVICES=8   train_scl_amlp_v4.py --alpha=0.5 --augNearRate=1000  --ent_open_scale=0.2 --gamma=0.1 --lr=0.02 --min_step=10000 --sigmaP=10 --sour_aug=0 --v_latent=10 --augNearRate=100000 --data_aug_crop 0.8 --config=configs/officehome-train-config_OPDA.yaml --source_data=./txt/source_Clipart_univ_zzl.txt --target_data=./txt/target_Real_univ_zzl.txt     &
CUDA_VISIBLE_DEVICES=9   train_scl_amlp_v4.py --alpha=0.5 --augNearRate=1000  --ent_open_scale=0.2 --gamma=0.1 --lr=0.02 --min_step=10000 --sigmaP=10 --sour_aug=0 --v_latent=10 --augNearRate=100000 --data_aug_crop 0.8 --config=configs/officehome-train-config_OPDA.yaml --source_data=./txt/source_Art_univ_zzl.txt     --target_data=./txt/target_Real_univ_zzl.txt     &
CUDA_VISIBLE_DEVICES=10  train_scl_amlp_v4.py --alpha=0.5 --augNearRate=1000  --ent_open_scale=0.2 --gamma=0.1 --lr=0.02 --min_step=10000 --sigmaP=10 --sour_aug=0 --v_latent=10 --augNearRate=100000 --data_aug_crop 0.8 --config=configs/officehome-train-config_OPDA.yaml --source_data=./txt/source_Art_univ_zzl.txt     --target_data=./txt/target_Clipart_univ_zzl.txt  &
CUDA_VISIBLE_DEVICES=11  train_scl_amlp_v4.py --alpha=0.5 --augNearRate=1000  --ent_open_scale=0.2 --gamma=0.1 --lr=0.02 --min_step=10000 --sigmaP=10 --sour_aug=0 --v_latent=10 --augNearRate=100000 --data_aug_crop 0.8 --config=configs/officehome-train-config_OPDA.yaml --source_data=./txt/source_Art_univ_zzl.txt     --target_data=./txt/target_Product_univ_zzl.txt 

CUDA_VISIBLE_DEVICES=0   train_scl_amlp_v4.py --alpha=0.5 --augNearRate=1000  --ent_open_scale=0.2 --gamma=0.1 --lr=0.02 --min_step=10000 --sigmaP=10 --sour_aug=0 --v_latent=20 --augNearRate=100000 --data_aug_crop 0.8 --config=configs/officehome-train-config_OPDA.yaml --source_data=./txt/source_Real_univ_zzl.txt    --target_data=./txt/target_Art_univ_zzl.txt      &
CUDA_VISIBLE_DEVICES=1   train_scl_amlp_v4.py --alpha=0.5 --augNearRate=1000  --ent_open_scale=0.2 --gamma=0.1 --lr=0.02 --min_step=10000 --sigmaP=10 --sour_aug=0 --v_latent=20 --augNearRate=100000 --data_aug_crop 0.8 --config=configs/officehome-train-config_OPDA.yaml --source_data=./txt/source_Real_univ_zzl.txt    --target_data=./txt/target_Clipart_univ_zzl.txt  &
CUDA_VISIBLE_DEVICES=2   train_scl_amlp_v4.py --alpha=0.5 --augNearRate=1000  --ent_open_scale=0.2 --gamma=0.1 --lr=0.02 --min_step=10000 --sigmaP=10 --sour_aug=0 --v_latent=20 --augNearRate=100000 --data_aug_crop 0.8 --config=configs/officehome-train-config_OPDA.yaml --source_data=./txt/source_Real_univ_zzl.txt    --target_data=./txt/target_Product_univ_zzl.txt  &
CUDA_VISIBLE_DEVICES=3   train_scl_amlp_v4.py --alpha=0.5 --augNearRate=1000  --ent_open_scale=0.2 --gamma=0.1 --lr=0.02 --min_step=10000 --sigmaP=10 --sour_aug=0 --v_latent=20 --augNearRate=100000 --data_aug_crop 0.8 --config=configs/officehome-train-config_OPDA.yaml --source_data=./txt/source_Product_univ_zzl.txt --target_data=./txt/target_Art_univ_zzl.txt      &
CUDA_VISIBLE_DEVICES=4   train_scl_amlp_v4.py --alpha=0.5 --augNearRate=1000  --ent_open_scale=0.2 --gamma=0.1 --lr=0.02 --min_step=10000 --sigmaP=10 --sour_aug=0 --v_latent=20 --augNearRate=100000 --data_aug_crop 0.8 --config=configs/officehome-train-config_OPDA.yaml --source_data=./txt/source_Product_univ_zzl.txt --target_data=./txt/target_Clipart_univ_zzl.txt  &
CUDA_VISIBLE_DEVICES=5   train_scl_amlp_v4.py --alpha=0.5 --augNearRate=1000  --ent_open_scale=0.2 --gamma=0.1 --lr=0.02 --min_step=10000 --sigmaP=10 --sour_aug=0 --v_latent=20 --augNearRate=100000 --data_aug_crop 0.8 --config=configs/officehome-train-config_OPDA.yaml --source_data=./txt/source_Product_univ_zzl.txt --target_data=./txt/target_Real_univ_zzl.txt     &
CUDA_VISIBLE_DEVICES=6   train_scl_amlp_v4.py --alpha=0.5 --augNearRate=1000  --ent_open_scale=0.2 --gamma=0.1 --lr=0.02 --min_step=10000 --sigmaP=10 --sour_aug=0 --v_latent=20 --augNearRate=100000 --data_aug_crop 0.8 --config=configs/officehome-train-config_OPDA.yaml --source_data=./txt/source_Clipart_univ_zzl.txt --target_data=./txt/target_Art_univ_zzl.txt      &
CUDA_VISIBLE_DEVICES=7   train_scl_amlp_v4.py --alpha=0.5 --augNearRate=1000  --ent_open_scale=0.2 --gamma=0.1 --lr=0.02 --min_step=10000 --sigmaP=10 --sour_aug=0 --v_latent=20 --augNearRate=100000 --data_aug_crop 0.8 --config=configs/officehome-train-config_OPDA.yaml --source_data=./txt/source_Clipart_univ_zzl.txt --target_data=./txt/target_Product_univ_zzl.txt  &
CUDA_VISIBLE_DEVICES=8   train_scl_amlp_v4.py --alpha=0.5 --augNearRate=1000  --ent_open_scale=0.2 --gamma=0.1 --lr=0.02 --min_step=10000 --sigmaP=10 --sour_aug=0 --v_latent=20 --augNearRate=100000 --data_aug_crop 0.8 --config=configs/officehome-train-config_OPDA.yaml --source_data=./txt/source_Clipart_univ_zzl.txt --target_data=./txt/target_Real_univ_zzl.txt     &
CUDA_VISIBLE_DEVICES=9   train_scl_amlp_v4.py --alpha=0.5 --augNearRate=1000  --ent_open_scale=0.2 --gamma=0.1 --lr=0.02 --min_step=10000 --sigmaP=10 --sour_aug=0 --v_latent=20 --augNearRate=100000 --data_aug_crop 0.8 --config=configs/officehome-train-config_OPDA.yaml --source_data=./txt/source_Art_univ_zzl.txt     --target_data=./txt/target_Real_univ_zzl.txt     &
CUDA_VISIBLE_DEVICES=10  train_scl_amlp_v4.py --alpha=0.5 --augNearRate=1000  --ent_open_scale=0.2 --gamma=0.1 --lr=0.02 --min_step=10000 --sigmaP=10 --sour_aug=0 --v_latent=20 --augNearRate=100000 --data_aug_crop 0.8 --config=configs/officehome-train-config_OPDA.yaml --source_data=./txt/source_Art_univ_zzl.txt     --target_data=./txt/target_Clipart_univ_zzl.txt  &
CUDA_VISIBLE_DEVICES=11  train_scl_amlp_v4.py --alpha=0.5 --augNearRate=1000  --ent_open_scale=0.2 --gamma=0.1 --lr=0.02 --min_step=10000 --sigmaP=10 --sour_aug=0 --v_latent=20 --augNearRate=100000 --data_aug_crop 0.8 --config=configs/officehome-train-config_OPDA.yaml --source_data=./txt/source_Art_univ_zzl.txt     --target_data=./txt/target_Product_univ_zzl.txt 

CUDA_VISIBLE_DEVICES=0   train_scl_amlp_v4.py --alpha=0.5 --augNearRate=1000  --ent_open_scale=0.2 --gamma=0.1 --lr=0.02 --min_step=10000 --sigmaP=10 --sour_aug=0 --v_latent=30 --augNearRate=100000 --data_aug_crop 0.8 --config=configs/officehome-train-config_OPDA.yaml --source_data=./txt/source_Real_univ_zzl.txt    --target_data=./txt/target_Art_univ_zzl.txt      &
CUDA_VISIBLE_DEVICES=1   train_scl_amlp_v4.py --alpha=0.5 --augNearRate=1000  --ent_open_scale=0.2 --gamma=0.1 --lr=0.02 --min_step=10000 --sigmaP=10 --sour_aug=0 --v_latent=30 --augNearRate=100000 --data_aug_crop 0.8 --config=configs/officehome-train-config_OPDA.yaml --source_data=./txt/source_Real_univ_zzl.txt    --target_data=./txt/target_Clipart_univ_zzl.txt  &
CUDA_VISIBLE_DEVICES=2   train_scl_amlp_v4.py --alpha=0.5 --augNearRate=1000  --ent_open_scale=0.2 --gamma=0.1 --lr=0.02 --min_step=10000 --sigmaP=10 --sour_aug=0 --v_latent=30 --augNearRate=100000 --data_aug_crop 0.8 --config=configs/officehome-train-config_OPDA.yaml --source_data=./txt/source_Real_univ_zzl.txt    --target_data=./txt/target_Product_univ_zzl.txt  &
CUDA_VISIBLE_DEVICES=3   train_scl_amlp_v4.py --alpha=0.5 --augNearRate=1000  --ent_open_scale=0.2 --gamma=0.1 --lr=0.02 --min_step=10000 --sigmaP=10 --sour_aug=0 --v_latent=30 --augNearRate=100000 --data_aug_crop 0.8 --config=configs/officehome-train-config_OPDA.yaml --source_data=./txt/source_Product_univ_zzl.txt --target_data=./txt/target_Art_univ_zzl.txt      &
CUDA_VISIBLE_DEVICES=4   train_scl_amlp_v4.py --alpha=0.5 --augNearRate=1000  --ent_open_scale=0.2 --gamma=0.1 --lr=0.02 --min_step=10000 --sigmaP=10 --sour_aug=0 --v_latent=30 --augNearRate=100000 --data_aug_crop 0.8 --config=configs/officehome-train-config_OPDA.yaml --source_data=./txt/source_Product_univ_zzl.txt --target_data=./txt/target_Clipart_univ_zzl.txt  &
CUDA_VISIBLE_DEVICES=5   train_scl_amlp_v4.py --alpha=0.5 --augNearRate=1000  --ent_open_scale=0.2 --gamma=0.1 --lr=0.02 --min_step=10000 --sigmaP=10 --sour_aug=0 --v_latent=30 --augNearRate=100000 --data_aug_crop 0.8 --config=configs/officehome-train-config_OPDA.yaml --source_data=./txt/source_Product_univ_zzl.txt --target_data=./txt/target_Real_univ_zzl.txt     &
CUDA_VISIBLE_DEVICES=6   train_scl_amlp_v4.py --alpha=0.5 --augNearRate=1000  --ent_open_scale=0.2 --gamma=0.1 --lr=0.02 --min_step=10000 --sigmaP=10 --sour_aug=0 --v_latent=30 --augNearRate=100000 --data_aug_crop 0.8 --config=configs/officehome-train-config_OPDA.yaml --source_data=./txt/source_Clipart_univ_zzl.txt --target_data=./txt/target_Art_univ_zzl.txt      &
CUDA_VISIBLE_DEVICES=7   train_scl_amlp_v4.py --alpha=0.5 --augNearRate=1000  --ent_open_scale=0.2 --gamma=0.1 --lr=0.02 --min_step=10000 --sigmaP=10 --sour_aug=0 --v_latent=30 --augNearRate=100000 --data_aug_crop 0.8 --config=configs/officehome-train-config_OPDA.yaml --source_data=./txt/source_Clipart_univ_zzl.txt --target_data=./txt/target_Product_univ_zzl.txt  &
CUDA_VISIBLE_DEVICES=8   train_scl_amlp_v4.py --alpha=0.5 --augNearRate=1000  --ent_open_scale=0.2 --gamma=0.1 --lr=0.02 --min_step=10000 --sigmaP=10 --sour_aug=0 --v_latent=30 --augNearRate=100000 --data_aug_crop 0.8 --config=configs/officehome-train-config_OPDA.yaml --source_data=./txt/source_Clipart_univ_zzl.txt --target_data=./txt/target_Real_univ_zzl.txt     &
CUDA_VISIBLE_DEVICES=9   train_scl_amlp_v4.py --alpha=0.5 --augNearRate=1000  --ent_open_scale=0.2 --gamma=0.1 --lr=0.02 --min_step=10000 --sigmaP=10 --sour_aug=0 --v_latent=30 --augNearRate=100000 --data_aug_crop 0.8 --config=configs/officehome-train-config_OPDA.yaml --source_data=./txt/source_Art_univ_zzl.txt     --target_data=./txt/target_Real_univ_zzl.txt     &
CUDA_VISIBLE_DEVICES=10  train_scl_amlp_v4.py --alpha=0.5 --augNearRate=1000  --ent_open_scale=0.2 --gamma=0.1 --lr=0.02 --min_step=10000 --sigmaP=10 --sour_aug=0 --v_latent=30 --augNearRate=100000 --data_aug_crop 0.8 --config=configs/officehome-train-config_OPDA.yaml --source_data=./txt/source_Art_univ_zzl.txt     --target_data=./txt/target_Clipart_univ_zzl.txt  &
CUDA_VISIBLE_DEVICES=11  train_scl_amlp_v4.py --alpha=0.5 --augNearRate=1000  --ent_open_scale=0.2 --gamma=0.1 --lr=0.02 --min_step=10000 --sigmaP=10 --sour_aug=0 --v_latent=30 --augNearRate=100000 --data_aug_crop 0.8 --config=configs/officehome-train-config_OPDA.yaml --source_data=./txt/source_Art_univ_zzl.txt     --target_data=./txt/target_Product_univ_zzl.txt 
